// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMqfvUevhL2HGVlm2YXGecii8vz6J2ncU',
    appId: '1:249761351129:android:5861d4e761c1dd5879c5c8',
    messagingSenderId: '249761351129',
    projectId: 'bazzarhub--app',
    storageBucket: 'bazzarhub--app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyMmjQwBAuFQOeRchbLqbyyDWejzI-e5w',
    appId: '1:249761351129:ios:84f3545ea1fc02d979c5c8',
    messagingSenderId: '249761351129',
    projectId: 'bazzarhub--app',
    storageBucket: 'bazzarhub--app.firebasestorage.app',
    androidClientId: '249761351129-f8lnrm5hjbvfbqtq617r2an9qtv47jhq.apps.googleusercontent.com',
    iosClientId: '249761351129-jc04d8q3cd3jefqe2lu3abgbe4f7t8a1.apps.googleusercontent.com',
    iosBundleId: 'com.example.bazzarHubApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt9kbbnkP9Ao9kTPEeBted8CmCAun8iNk',
    appId: '1:249761351129:web:7ef1f12247ee4a1479c5c8',
    messagingSenderId: '249761351129',
    projectId: 'bazzarhub--app',
    authDomain: 'bazzarhub--app.firebaseapp.com',
    storageBucket: 'bazzarhub--app.firebasestorage.app',
  );

}